//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Poc and Personal\dslq\Demo.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DemoParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IDemoListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemoParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] DemoParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemoParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] DemoParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>compareExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareExp([NotNull] DemoParser.CompareExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>compareExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareExp([NotNull] DemoParser.CompareExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>andLogicalExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndLogicalExp([NotNull] DemoParser.AndLogicalExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>andLogicalExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndLogicalExp([NotNull] DemoParser.AndLogicalExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>bracketExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBracketExp([NotNull] DemoParser.BracketExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>bracketExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBracketExp([NotNull] DemoParser.BracketExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>orLogicalExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOrLogicalExp([NotNull] DemoParser.OrLogicalExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>orLogicalExp</c>
	/// labeled alternative in <see cref="DemoParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOrLogicalExp([NotNull] DemoParser.OrLogicalExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DemoParser.attrPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttrPath([NotNull] DemoParser.AttrPathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DemoParser.attrPath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttrPath([NotNull] DemoParser.AttrPathContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boolean</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] DemoParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boolean</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] DemoParser.BooleanContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>null</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNull([NotNull] DemoParser.NullContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>null</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNull([NotNull] DemoParser.NullContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] DemoParser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>string</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] DemoParser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>double</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDouble([NotNull] DemoParser.DoubleContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>double</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDouble([NotNull] DemoParser.DoubleContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>long</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLong([NotNull] DemoParser.LongContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>long</c>
	/// labeled alternative in <see cref="DemoParser.attrValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLong([NotNull] DemoParser.LongContext context);
}
